# agents/apply_agent.py
import requests
import time

class ApplyAgent:
    """
    Uses the artifacts generated by ArtifactAgent to apply for jobs.
    Submits to a sandbox portal for demo purposes.
    """

    def __init__(self, portal_url: str):
        self.portal_url = portal_url

    def apply(self, job: dict, artifacts: dict, retries: int = 3) -> dict:
        """
        job: a single job dictionary (job_id, title, description, company, etc.)
        artifacts: output of ArtifactAgent.run()
            - profile
            - bullet_bank
            - proof_pack
        """

        payload = {
            "job_id": job.get("job_id"),
            "student_name": artifacts["profile"].get("name", "Anonymous"),
            "resume": "base_resume_placeholder",  # for demo, could be PDF text
            "bullets": [b["bullet"] for b in artifacts.get("bullet_bank", [])],
            "proofs": artifacts.get("proof_pack", [])
        }

        for attempt in range(1, retries + 1):
            try:
                res = requests.post(f"{self.portal_url}/apply", json=payload, timeout=5)
                res.raise_for_status()
                data = res.json()

                if data.get("status") == "submitted":
                    return {
                        "success": True,
                        "application_id": data.get("application_id")
                    }
                else:
                    # failed submission (sandbox random failure)
                    time.sleep(1)

            except Exception as e:
                # network or server error, retry
                time.sleep(1)

        # max retries exceeded
        return {"success": False, "reason": "Max retries exceeded"}
